resources:
- manager.yaml
- image-based-install-operator-networkpolicy.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: controller
  newTag: latest
