# permissions for end users to edit imageclusterinstalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imageclusterinstall-editor
rules:
- apiGroups:
  - relocation.openshift.io
  resources:
  - imageclusterinstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relocation.openshift.io
  resources:
  - imageclusterinstalls/status
  verbs:
  - get
