// Code generated by MockGen. DO NOT EDIT.
// Source: installer.go
//
// Generated by this command:
//
//	mockgen -source=installer.go -package=installer -destination=mock_installer.go
//

// Package installer is a generated GoMock package.
package installer

import (
	context "context"
	reflect "reflect"

	credentials "github.com/openshift/image-based-install-operator/internal/credentials"
	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

// MockInstaller is a mock of Installer interface.
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller.
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance.
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// CreateInstallationIso mocks base method.
func (m *MockInstaller) CreateInstallationIso(ctx context.Context, log logrus.FieldLogger, workDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInstallationIso", ctx, log, workDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInstallationIso indicates an expected call of CreateInstallationIso.
func (mr *MockInstallerMockRecorder) CreateInstallationIso(ctx, log, workDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstallationIso", reflect.TypeOf((*MockInstaller)(nil).CreateInstallationIso), ctx, log, workDir)
}

// WriteReinstallData mocks base method.
func (m *MockInstaller) WriteReinstallData(ctx context.Context, tmpWorkDir, isoWorkDir string, idData credentials.IdentityData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteReinstallData", ctx, tmpWorkDir, isoWorkDir, idData)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteReinstallData indicates an expected call of WriteReinstallData.
func (mr *MockInstallerMockRecorder) WriteReinstallData(ctx, tmpWorkDir, isoWorkDir, idData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteReinstallData", reflect.TypeOf((*MockInstaller)(nil).WriteReinstallData), ctx, tmpWorkDir, isoWorkDir, idData)
}
